### ISSUE TITLE
Cosmetic: line swhowing Score, Depth…

### ISSUE THREAD

**Issue by speciale** [daylen/stockfish-mac#32] opened 2017-08-24 16:08 UTC
First, I must say that it's an excellent software. Thanks. 
Then, the line showing the Score, Depth, Current, move Speed, MultiPV doesn't adjust to the width of the parent window and it causes jumps when the size is little.
Thank you again

**Comment by daylen** [comment] 2018-01-05 09:02
Dupe of #20

**Closed by daylen** 2018-01-05 09:02 UTC
